### PR TITLE
Implement JSON logging.

### PR DESCRIPTION
**Pull request by tomgco**
Due to some added logging, the coverage of this pull request falls.

### CODE REVIEW

**Comment by nelsonic** [comment]
@tomgco, 
I'm not a fan of the 

``` js
if(err) {
  AwsHelper.log.error({ err: err }, 'Unable to connect to geonames cache');
}
```

see: https://codecov.io/gh/numo-labs/lambda-taggable-geonames-indexer/src/ddb17bfa4f13e190e0c0f08b75e7aa29e7a6121d/lib/geonames.js#L56

_Instead_ I propose that the `if(err)` takes place inside the `AwsHelper.log.error` method.
(_Similar to how [`Hoek.assert`](https://github.com/hapijs/hoek/blob/master/API.md#assertcondition-message) works..._) So we can keep our error checking/handling to one-line. e.g:

``` js
http_request(options, function (err, hierarchy) {
  AwsHelper.log.error({ err: err }, 'Unable to connect to geonames cache'); // AwsHelper ignores if err is null.
// continue with what we were doing ...
}
```

We are committed to maintaining 100% coverage in all our open-source (_show-case_) Lambdas ...

**Comment by tomgco** [comment]
Thanks for the reply @nelsonic, 

I understand that want for 100% code-coverage in projects, however in an ideal world, we would handle all of these potential error paths and callback to notify of said errors instead of asserting and throwing but that was outside the scope of the PR. 

I am happy to remove those offending lines in this PR now as we are actually catching all of the errors and logging them within `aws-lambda-hepler`.

**Comment by tomgco** [comment]
Okay Dokie, @nelsonic I have removed the

```
if (err) {
...
}
```

code blocks. And should be ready to merge.

**Comment by hassy** [comment]
Logging stuff lgtm 👍

**Comment by nelsonic** [comment]
Thanks! 👍

**Pull request merged**
